// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOmDT9WDsguHPQtK5YnL_bsbpr2c6sw8k',
    appId: '1:720182226573:web:e18495740b0aee98bbbcc4',
    messagingSenderId: '720182226573',
    projectId: 'push-notification-63a01',
    authDomain: 'push-notification-63a01.firebaseapp.com',
    storageBucket: 'push-notification-63a01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy6rFNi-XoDqyEwzd4A9_2gMx9uc50dQ4',
    appId: '1:720182226573:android:b644717162845fd1bbbcc4',
    messagingSenderId: '720182226573',
    projectId: 'push-notification-63a01',
    storageBucket: 'push-notification-63a01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvOe126w_d-gTzB4D-uGGvbXwVQ_Ne9f8',
    appId: '1:720182226573:ios:4dc67cc9a52ff993bbbcc4',
    messagingSenderId: '720182226573',
    projectId: 'push-notification-63a01',
    storageBucket: 'push-notification-63a01.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvOe126w_d-gTzB4D-uGGvbXwVQ_Ne9f8',
    appId: '1:720182226573:ios:4dc67cc9a52ff993bbbcc4',
    messagingSenderId: '720182226573',
    projectId: 'push-notification-63a01',
    storageBucket: 'push-notification-63a01.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOmDT9WDsguHPQtK5YnL_bsbpr2c6sw8k',
    appId: '1:720182226573:web:eaf223e3108574a4bbbcc4',
    messagingSenderId: '720182226573',
    projectId: 'push-notification-63a01',
    authDomain: 'push-notification-63a01.firebaseapp.com',
    storageBucket: 'push-notification-63a01.appspot.com',
  );

}