// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf6y6gpBITMCBGmcMpDTm-3Ee5UE1CzYE',
    appId: '1:1093519072396:web:057f8074236b5a0e59efa9',
    messagingSenderId: '1093519072396',
    projectId: 'flutter-notification-91ae5',
    authDomain: 'flutter-notification-91ae5.firebaseapp.com',
    storageBucket: 'flutter-notification-91ae5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBryUCz56hUWzs113dywm5a5tKmeVnrG4o',
    appId: '1:1093519072396:android:344961ce335b649c59efa9',
    messagingSenderId: '1093519072396',
    projectId: 'flutter-notification-91ae5',
    storageBucket: 'flutter-notification-91ae5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALMyPOeAoyM6K8Qs78eHJ99D9Vaxliw0E',
    appId: '1:1093519072396:ios:777abb6e9019e4b159efa9',
    messagingSenderId: '1093519072396',
    projectId: 'flutter-notification-91ae5',
    storageBucket: 'flutter-notification-91ae5.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALMyPOeAoyM6K8Qs78eHJ99D9Vaxliw0E',
    appId: '1:1093519072396:ios:777abb6e9019e4b159efa9',
    messagingSenderId: '1093519072396',
    projectId: 'flutter-notification-91ae5',
    storageBucket: 'flutter-notification-91ae5.appspot.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf6y6gpBITMCBGmcMpDTm-3Ee5UE1CzYE',
    appId: '1:1093519072396:web:54c21aa42f95e7ba59efa9',
    messagingSenderId: '1093519072396',
    projectId: 'flutter-notification-91ae5',
    authDomain: 'flutter-notification-91ae5.firebaseapp.com',
    storageBucket: 'flutter-notification-91ae5.appspot.com',
  );

}